### DISCUSSION TITLE
Code style and lints.

### DISCUSSION THREAD

**Discussion by ykmnkmi** [angulardart-community/angular#35] [General]
Any rules/restrictions on code style?

For example, `ngast\test\ast_cli_tester.dart`:
```dart
import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:ngast/ngast.dart';

RecoveringExceptionHandler exceptionHandler = RecoveringExceptionHandler();

List<StandaloneTemplateAst> parse(String template) => const NgParser().parse(
      template,
      sourceUrl: '/test/parser_test.dart#inline',
      exceptionHandler: exceptionHandler,
      desugar: false,
    );

void main() {
  String input;
  exceptionHandler.exceptions.clear();
  var fileDir = p.join('test', 'ast_cli_tester_source.html');
  var file = File(fileDir.toString());
  input = file.readAsStringSync();
  //input = stdin.readLineSync(encoding: UTF8);
  var ast = parse(input);
  print('----------------------------------------------');
  if (exceptionHandler is ThrowingExceptionHandler) {
    print('CORRECT!');
    print(ast);
  }
  var exceptionsList = exceptionHandler.exceptions;
  if (exceptionsList.isEmpty) {
    print('CORRECT!');
    print(ast);
  } else {
    var visitor = const HumanizingTemplateAstVisitor();
    var fixed = ast.map((t) => t.accept(visitor)).join('');
    print('ORGNL: $input');
    print('FIXED: $fixed');

    print('\n\nERRORS:');
    for (var e in exceptionHandler.exceptions) {
      var context = input.substring(e.offset!, e.offset! + e.length!);
      print('${e.errorCode.message} :: $context at ${e.offset}');
    }
  }
}
```
I would rewrite like this:
```dart
import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:ngast/ngast.dart';

// global & no use outside - without type
final exceptionHandler = RecoveringExceptionHandler();

// not function literal - full function
List<StandaloneTemplateAst> parse(String template) {
  return const NgParser().parse(
    template,
    sourceUrl: '/test/parser_test.dart#inline',
    exceptionHandler: exceptionHandler,
    desugar: false,
  );
}

void main() {
  exceptionHandler.exceptions.clear();

  // empty line before variable declaration
  var fileDir = p.join('test', 'ast_cli_tester_source.html');
  var file = File(fileDir);
  var input = file.readAsStringSync();
  var ast = parse(input);
  print('----------------------------------------------');

  // empty line around blocks
  if (exceptionHandler is ThrowingExceptionHandler) {
    print('CORRECT!');
    print(ast);
  }

  var exceptionsList = exceptionHandler.exceptions;

  if (exceptionsList.isEmpty) {
    print('CORRECT!');
    print(ast);
  } else {
    var visitor = const HumanizingTemplateAstVisitor();
    var fixed = ast.map((t) => t.accept(visitor)).join();
    print('ORGNL: $input');
    print('FIXED: $fixed');

    print('\n\nERRORS:');

    for (var e in exceptionHandler.exceptions) {
      var context = input.substring(e.offset!, e.offset! + e.length!);
      print('${e.errorCode.message} :: $context at ${e.offset}');
    }
  }
}
```

My default `analysis_options.yaml` config:
```yaml
include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    avoid_dynamic_calls: true
    avoid_escaping_inner_quotes: true
    avoid_final_parameters: true
    avoid_print: true
    avoid_void_async: true
    combinators_ordering: true
    directives_ordering: true
    prefer_single_quotes: true
    unnecessary_final: true
    unnecessary_lambdas: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    use_super_parameters: true
```
