### ISSUE TITLE
Angular compiler is eliminating CSS Container Queries from a component's CSS file

### ISSUE THREAD

**Issue by insinfo** [angulardart-community/angular#57]
### Which ng* package(s) are the source of the bug?

ngcompiler, ngdart

### Which operating system(s) does this bug appear on?

Windows

### Which browser(s) does this bug appear on?

Chrome 113.0.5672.93

### Is this a regression?

No

### Description

Angular compiler is eliminating CSS Container Queries from a component's CSS file, is there any way to prevent this?

### Please provide the steps to reproduce the bug

create a new dart web project add ngdart: ^7.1.1 create a component and add a css file using annotation and put

```css
.grid-layout {    
    gap: 1.25rem;
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;   
    container-type: inline-size;  
}
/*col-sm ≥576px */
@container (min-width: 576px) {
    .grid-item {
        background: red;
        width: calc((100% / 2) - 1.0rem);
    }
}

/*md ≥768px*/
@container (min-width: 768px) {
    .grid-item {
        background: blue;
        width: calc((100% / 2) - 1.0rem);
    }
}
```

### Please provide the exception or error you saw

```true
[WARNING] ngdart on lib/src/shared/components/datatable/grid.css: Errors parsing CSS:
error on line 51, column 12: expected :, but found (
   ╷
51 │ @container (min-width: 576px) {
   │            ^
   ╵
error on line 51, column 24: premature end of file unknown CSS
   ╷
51 │ @container (min-width: 576px) {
   │                        ^^^
```

### Please provide the dependency environment you discovered this bug in (run `dart pub deps -s compact`)

```true
Dart SDK version: 2.18.3

environment:   
  sdk: '>=2.18.0 <3.0.0'

dependencies:   
  ngdart: ^7.1.1 
  ngforms: ^4.1.1
  ngrouter: ^3.1.1   

dev_dependencies:   
  sass_builder: ^2.1.2 
  build_runner: any
  build_test: any
  build_web_compilers: any
  pedantic: any
  test: any
```
